<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="HeaderFonts.ascx.cs" Inherits="SwetNation.Web.controls.HeaderFonts" %>
<link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Forum&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bowlby+One+SC&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lobster+Two&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Redressed&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Goblin+One&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aclonica&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jura&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Caudex&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kameron&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Podkova&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sigmar+One&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=UnifrakturCook:bold&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=News+Cycle&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Round&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:100&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crimson+Text:regular,regularitalic,600,600italic,bold,bolditalic' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Artifika&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Nunito&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:bold&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Shanti' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Mako' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Lobster&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Michroma&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Bevan&v1' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Terminal+Dosis+Light' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Crushed' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Puritan' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Anonymous+Pro' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=OFL+Sorts+Mill+Goudy+TT' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Nobile' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Didact+Gothic' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=News+Cycle' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Kreon' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Radley' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Bentham' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,400italic' rel='stylesheet' type='text/css'/>
<link href="http://fonts.googleapis.com/css?family=Terminal+Dosis:300,400,500" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Cantata+One:400normal&subset=all' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Advent+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>